"""empty message

Revision ID: d6de294533e2
Revises: 163cd5ea0ead
Create Date: 2022-01-11 10:37:35.471456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6de294533e2'
down_revision = '163cd5ea0ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address_line_1', sa.String(length=150), nullable=True),
    sa.Column('address_line_2', sa.String(length=150), nullable=True),
    sa.Column('town', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('telephone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('school_image_link', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authority.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    # ### end Alembic commands ###
