"""empty message

Revision ID: 05b91233f968
Revises: 33d34331f3d4
Create Date: 2022-01-11 10:42:33.956401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b91233f968'
down_revision = '33d34331f3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audit_date', sa.DateTime(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('primary_key_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit')
    # ### end Alembic commands ###
