"""empty message

Revision ID: 154dbeb3a4ee
Revises: d4d869d57683
Create Date: 2022-03-28 21:44:08.789130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '154dbeb3a4ee'
down_revision = 'd4d869d57683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('description', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
