"""empty message

Revision ID: 16abc82633a7
Revises: b3104173e097
Create Date: 2022-04-16 21:50:45.104880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16abc82633a7'
down_revision = 'b3104173e097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node_sensor', sa.Column('cube_level', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node_sensor', 'cube_level')
    # ### end Alembic commands ###
