"""empty message

Revision ID: 235f16669d4d
Revises: f3a78022fc58
Create Date: 2022-02-08 10:43:23.044574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235f16669d4d'
down_revision = 'f3a78022fc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
