"""empty message

Revision ID: 439d001807fd
Revises: 71a6491bfe88
Create Date: 2022-04-05 17:05:56.436673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '439d001807fd'
down_revision = '71a6491bfe88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiment', 'description',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.drop_column('tag_reference', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_reference', sa.Column('label', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('experiment', 'description',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
