"""empty message

Revision ID: 60d5b093879b
Revises: 75d55ff74fef
Create Date: 2022-03-25 16:50:57.504138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60d5b093879b'
down_revision = '75d55ff74fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('condition', 'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('condition', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('experiment', 'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('experiment', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('experiment', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('experiment', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('experiment', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('experiment_participant', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('hypothesis', 'hypothesis_no',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('hypothesis', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('hypothesis', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('node_alert', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('node_alert', 'created_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('node_alert', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('node_sensor', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('observation', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('project', 'title',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('project', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('project', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('project', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('project', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('project_leader', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('project_partner', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('question', 'response_type',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('question', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('report', 'report_stage',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('report', 'report_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('report', 'title',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('report', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('school', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('school', 'town',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('school', 'postcode',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('school', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('school', 'postcode',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('school', 'town',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('school', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('report', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('report', 'title',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('report', 'report_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('report', 'report_stage',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('question', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('question', 'response_type',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('project_partner', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('project_leader', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('project', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('project', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('project', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('project', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('project', 'title',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('observation', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('node_sensor', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('node_alert', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('node_alert', 'created_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('node_alert', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('hypothesis', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('hypothesis', 'description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('hypothesis', 'hypothesis_no',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('experiment_participant', 'status',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('experiment', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('experiment', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('experiment', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('experiment', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('experiment', 'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('condition', 'status',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.alter_column('condition', 'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
