"""empty message

Revision ID: 6e146793aa20
Revises: a2d23152740a
Create Date: 2022-04-26 19:53:31.443318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e146793aa20'
down_revision = 'a2d23152740a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('reported_date', sa.DateTime(), nullable=False),
    sa.Column('symptoms', sa.String(length=5000), nullable=False),
    sa.Column('steps_to_reproduce', sa.String(length=5000), nullable=False),
    sa.Column('notes', sa.String(length=5000), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue')
    # ### end Alembic commands ###
