"""empty message

Revision ID: 75d55ff74fef
Revises: 6e67b963768a
Create Date: 2022-03-25 16:24:51.320479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75d55ff74fef'
down_revision = '6e67b963768a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('domain', sa.String(length=30), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_status_id', sa.Integer(), nullable=False),
    sa.Column('to_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['to_status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('procedure', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], ['variable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=True),
    sa.Column('tuesday', sa.Boolean(), nullable=True),
    sa.Column('wednesday', sa.Boolean(), nullable=True),
    sa.Column('thursday', sa.Boolean(), nullable=True),
    sa.Column('friday', sa.Boolean(), nullable=True),
    sa.Column('saturday', sa.Boolean(), nullable=True),
    sa.Column('sunday', sa.Boolean(), nullable=True),
    sa.Column('final', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condition_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('experiment_variable_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ),
    sa.ForeignKeyConstraint(['experiment_variable_id'], ['experiment_variable.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('cube_level', sa.String(length=10), nullable=True),
    sa.Column('replicate_no', sa.Integer(), nullable=True),
    sa.Column('row', sa.String(length=1), nullable=True),
    sa.Column('column', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('observation', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.add_column('observation', sa.Column('condition_variable_id', sa.Integer(), nullable=False))
    op.drop_constraint('observation_ibfk_2', 'observation', type_='foreignkey')
    op.create_foreign_key(None, 'observation', 'condition_variable', ['condition_variable_id'], ['id'])
    op.create_foreign_key(None, 'observation', 'unit', ['unit_id'], ['id'])
    op.drop_column('observation', 'variable_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column('variable_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.create_foreign_key('observation_ibfk_2', 'observation', 'variable', ['variable_id'], ['id'])
    op.drop_column('observation', 'condition_variable_id')
    op.drop_column('observation', 'unit_id')
    op.drop_table('unit')
    op.drop_table('condition_variable')
    op.drop_table('experiment_variable')
    op.drop_table('level')
    op.drop_table('transition')
    op.drop_table('status')
    # ### end Alembic commands ###
