"""empty message

Revision ID: 7d9a20737f4f
Revises: 235f16669d4d
Create Date: 2022-02-22 21:02:46.959084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d9a20737f4f'
down_revision = '235f16669d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'experiment', 'project', ['project_id'], ['id'])
    op.drop_column('experiment', 'partner_id')
    op.create_foreign_key(None, 'experiment_participant', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'experiment_participant', 'experiment', ['experiment_id'], ['id'])
    op.create_foreign_key(None, 'node_sensor', 'node', ['node_id'], ['id'])
    op.create_foreign_key(None, 'node_sensor', 'sensor', ['sensor_id'], ['id'])
    op.create_foreign_key(None, 'observation', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'observation', 'variable', ['variable_id'], ['id'])
    op.drop_index('user_id', table_name='project_leader')
    op.create_foreign_key(None, 'project_leader', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project_leader', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'project_partner', 'school', ['school_id'], ['id'])
    op.create_foreign_key(None, 'project_partner', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'question', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'question', 'experiment', ['experiment_id'], ['id'])
    op.add_column('report', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('report', sa.Column('experiment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'report', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'report', 'experiment', ['experiment_id'], ['id'])
    op.drop_column('report', 'updated_date')
    op.drop_column('report', 'report_type')
    op.drop_column('report', 'parent_id')
    op.drop_column('report', 'created_by')
    op.drop_column('report', 'created_date')
    op.create_foreign_key(None, 'response', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'response', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'sensor_quantity', 'quantity', ['quantity_id'], ['id'])
    op.add_column('tag', sa.Column('experiment_id', sa.String(length=300), nullable=False))
    op.add_column('tag', sa.Column('tag_reference_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'tag', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'tag', 'experiment', ['experiment_id'], ['id'])
    op.create_foreign_key(None, 'tag', 'tag_reference', ['tag_reference_id'], ['id'])
    op.drop_column('tag', 'partner_id')
    op.drop_column('tag', 'title')
    op.drop_column('tag', 'experiment_image_link')
    op.drop_column('tag', 'end_date')
    op.drop_column('tag', 'experiment_text')
    op.drop_column('tag', 'is_synchronised')
    op.drop_column('tag', 'description')
    op.drop_column('tag', 'start_date')
    op.drop_column('tag', 'status')
    op.create_foreign_key(None, 'variable', 'node_sensor', ['node_sensor_id'], ['id'])
    op.create_foreign_key(None, 'variable', 'quantity', ['quantity_id'], ['id'])
    op.create_foreign_key(None, 'variable', 'condition', ['condition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variable', type_='foreignkey')
    op.drop_constraint(None, 'variable', type_='foreignkey')
    op.drop_constraint(None, 'variable', type_='foreignkey')
    op.add_column('tag', sa.Column('status', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('tag', sa.Column('start_date', sa.DATE(), nullable=True))
    op.add_column('tag', sa.Column('description', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('tag', sa.Column('is_synchronised', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('experiment_text', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('tag', sa.Column('end_date', sa.DATE(), nullable=True))
    op.add_column('tag', sa.Column('experiment_image_link', mysql.VARCHAR(length=300), nullable=True))
    op.add_column('tag', sa.Column('title', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('tag', sa.Column('partner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'tag_reference_id')
    op.drop_column('tag', 'experiment_id')
    op.drop_constraint(None, 'sensor_quantity', type_='foreignkey')
    op.drop_constraint(None, 'response', type_='foreignkey')
    op.drop_constraint(None, 'response', type_='foreignkey')
    op.add_column('report', sa.Column('created_date', mysql.DATETIME(), nullable=True))
    op.add_column('report', sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('report', sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('report', sa.Column('report_type', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('report', sa.Column('updated_date', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'experiment_id')
    op.drop_column('report', 'project_id')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'project_partner', type_='foreignkey')
    op.drop_constraint(None, 'project_partner', type_='foreignkey')
    op.drop_constraint(None, 'project_leader', type_='foreignkey')
    op.drop_constraint(None, 'project_leader', type_='foreignkey')
    op.create_index('user_id', 'project_leader', ['user_id'], unique=False)
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.drop_constraint(None, 'node_sensor', type_='foreignkey')
    op.drop_constraint(None, 'node_sensor', type_='foreignkey')
    op.drop_constraint(None, 'experiment_participant', type_='foreignkey')
    op.drop_constraint(None, 'experiment_participant', type_='foreignkey')
    op.add_column('experiment', sa.Column('partner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    # ### end Alembic commands ###
