"""empty message

Revision ID: 836856b60899
Revises: 6e146793aa20
Create Date: 2022-08-08 15:55:07.168085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836856b60899'
down_revision = '6e146793aa20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variable', sa.Column('is_treatment', sa.Boolean(), nullable=True))
    op.add_column('variable', sa.Column('is_response', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variable', 'is_response')
    op.drop_column('variable', 'is_treatment')
    # ### end Alembic commands ###
