"""empty message

Revision ID: 8f39258ad8c5
Revises: edc1946b2917
Create Date: 2022-03-30 20:12:55.207660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f39258ad8c5'
down_revision = 'edc1946b2917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('col', sa.Integer(), nullable=True))
    op.drop_column('unit', 'column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('column', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('unit', 'col')
    # ### end Alembic commands ###
