"""empty message

Revision ID: b1c67a7ba703
Revises: 836856b60899
Create Date: 2022-08-08 22:03:02.090661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c67a7ba703'
down_revision = '836856b60899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'variable', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variable', type_='unique')
    # ### end Alembic commands ###
