"""empty message

Revision ID: d74b9cd15141
Revises: 8f39258ad8c5
Create Date: 2022-03-30 20:19:28.257280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd74b9cd15141'
down_revision = '8f39258ad8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('grid_row', sa.String(length=1), nullable=True))
    op.add_column('unit', sa.Column('grid_column', sa.Integer(), nullable=True))
    op.drop_column('unit', 'col')
    op.drop_column('unit', 'row')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('row', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('unit', sa.Column('col', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('unit', 'grid_column')
    op.drop_column('unit', 'grid_row')
    # ### end Alembic commands ###
