"""empty message

Revision ID: dbc2ffa82046
Revises: 25027e519d2e
Create Date: 2022-01-11 16:56:56.459885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbc2ffa82046'
down_revision = '25027e519d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quantity', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.drop_index('name', table_name='quantity')
    op.alter_column('users', 'school_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('users', 'is_sysadmin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'is_sysadmin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'school_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index('name', 'quantity', ['name'], unique=False)
    op.alter_column('quantity', 'name',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
