"""empty message

Revision ID: e83555ce900f
Revises: dbc2ffa82046
Create Date: 2022-01-18 10:26:23.638413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e83555ce900f'
down_revision = 'dbc2ffa82046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_date')
    op.drop_column('users', 'updated_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_date', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('created_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
