"""empty message

Revision ID: fa3f01a54dbb
Revises: 235f16669d4d
Create Date: 2022-02-08 12:31:39.675737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3f01a54dbb'
down_revision = '235f16669d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='audit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id', 'audit', ['user_id'], unique=False)
    # ### end Alembic commands ###
